return {
  borders = {
    TopRightCorner = "┐",
    TopLeftCorner = "┌",
    HorizontalEdge = "─",
    TeeDownEdge = "┬",
    TeeUpEdge = "┴",
    BottomRightCorner = "┘",
    BottomLeftCorner = "└",
    VerticalEdge = "│",
    Cross = "┼",
    TeeLeft = "┤",
    TeeRight = "├",
    DoubleTopRightCorner = "╗",
    DoubleTopLeftCorner = "╔",
    DoubleHorizontalEdge = "═",
    DoubleTeeDownEdge = "╦",
    DoubleTeeUpEdge = "╩",
    DoubleBottomRightCorner = "╝",
    DoubleBottomLeftCorner = "╚",
    DoubleVerticalEdge = "║",
    DoubleCross = "╬",
    DoubleTeeLeft = "╣",
    DoubleTeeRight = "╠",
    XCross = "╳",
    DownSlant = "╲",
    UpSlant = "╱"
  },
  arrows = {
    Left = "▶",
    Right = "◀",
    Up = "▲",
    Down = "▼",
    OpenLeft = "▷",
    OpenRight = "◁",
    OpenUp = "△",
    OpenDown = "▽",
  }
}
